version: "3"
services: 
  web: 
    build: .
    container_name: email-service
    networks:
      - app-network
    depends_on:
      - mongodb
    links: 
      - mongodb
    env_file:
      - .env
    ports:
      - "3500:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongo-service
    env_file:
      - .env
    networks:
      - app-network

volumes:
  .: 

networks:
  app-network:
    external:
      name: fls-pid_app-network
